# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Arnab Roy
subtitle: 
email: 
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
footer_text: >
  Built with Jekyll, Gradfolio and Al-folio.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" #https://byt3bit.github.io # the base hostname & protocol for your site, e.g. http://example.com
keywords: #cryptography, Arnab, Roy, algebraic, cryptanalysis, cryptography


# -----------------------------------------------------------------------------
# Generic layout
# -----------------------------------------------------------------------------
navbar_fixed: true
footer_fixed: true
bib_search: false
footer_social: false  #change to include social icons on footer 
# -----------------------------------------------------------------------------
# Width of your website 
# -----------------------------------------------------------------------------
max_width: 930px

# -----------------------------------------------------------------------------
# Repo Color themes
# -----------------------------------------------------------------------------
repo_theme_light: default # https://github.com/anuraghazra/github-readme-stats/blob/master/themes/README.md
repo_theme_dark: dark # https://github.com/anuraghazra/github-readme-stats/blob/master/themes/README.md


enable_address_social: false # for including social icons under image
enable_navbar_social: true  # social icons on navbar 
# -----------------------------------------------------------------------------
# GitHub settings 
# -----------------------------------------------------------------------------
github_username: byt3bit
repo_description_lines_max: 3
github_repos: # here you can put a list of  your selected repositories

# -----------------------------------------------------------------------------
# Social Media links (put only the usernames)
### Comment the social you don't want to add to your footer
# -----------------------------------------------------------------------------
# twitter: "#"
# linkedin: "#"
# stackoverflow: "#"
github: byt3bit
# researchgate: "#"
orcid: 0000-0002-3284-7076
google_scholar: 1y6FMuYAAAAJ&hl=en
dblp: 88/4138-5.html
# quora: "#"
# instagram: "#"
# facebook: "#"
#social_data:
#  github_username: byt3bit
#  orcid_id: 0000-0002-3284-7076

# -----------------------------------------------------------------------------
# Jekyll Scholar
# -----------------------------------------------------------------------------

scholar:
  last_name: [Roy]
  first_name: [Arnab]

  style: apa
  locale: en

  source: /_bibliography/
  bibliography: example.bib
  bibliography_template: bib
  bibtex_filters: [latex, smallcaps, superscript]

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_link: Details

  query: "@*"
  # group_by: year
  # group_order: descending

  sort_by: year
  order: descending


# Maximum number of authors to be shown for each publication (more authors are visible on click)
max_author_limit: # leave blank to always show all authors
more_authors_animation_delay: 10 # more authors are revealed on click using animation; smaller delay means faster animation



################################################################
############### DON'T TOUCH FROM HERE ##########################
################################################################
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
include: ["_pages"]
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/


sass:
  sass_dir: /assets/css/_sass
  style: compressed

# Build settings
# theme: minima
plugins:
  - jekyll/scholar

# Markdown
highlighter: rouge
markdown: kramdown

## Necessary libraries for UI&UX
third_party_libraries:
  download: false # if true, download the versions of the libraries specified below and use the downloaded files
  bootstrap-table:
    integrity:
      css: #"sha256-uRX+PiRTR4ysKFRCykT8HLuRCub26LgXJZym3Yeom1c="
      js: #"sha256-4rppopQE9POKfukn2kEvhJ9Um25Cf6+IDVkARD0xh78="
    url:
      css: "https://cdn.jsdelivr.net/npm/bootstrap-table@1.23.5/dist/bootstrap-table.min.css"
      js: "https://cdn.jsdelivr.net/npm/bootstrap-table@1.23.5/dist/bootstrap-table.min.js"
    version: "1.23.5"
  google_fonts:
    url:
      fonts: "https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:100,300,400,500,700|Material+Icons&display=swap"
  jquery:
    integrity:
      js: "sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo="
    url:
      js: "https://code.jquery.com/jquery-3.7.1.min.js"
    version: "3.7.1"